# Generated by Django 2.0.2 on 2019-08-05 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190725_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(default=245101)),
                ('purpose', models.CharField(blank=True, max_length=100)),
                ('whoto', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=70)),
                ('phone', models.IntegerField(default=9897654568)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='visitor_perma',
            name='gender',
        ),
        migrations.AddField(
            model_name='visitor_perma',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='visitor_perma',
            name='email',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='visitor_perma',
            name='phone',
            field=models.IntegerField(default=9897632545),
        ),
        migrations.AddField(
            model_name='visitor_perma',
            name='whoto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='temp',
            name='gender',
            field=models.CharField(max_length=100),
        ),
    ]
