# Generated by Django 2.0.2 on 2019-08-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190805_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
